import { StyleSheet } from 'react-native';
import { theme } from '../../theme/theme';
import { CARD_WIDTH } from './constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: theme.spacing.md,
    paddingTop: theme.spacing.sm,
    paddingBottom: theme.spacing.xs,
    backgroundColor: theme.colors.background,
  },
  infoButtonInline: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.cardBg,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabBtnActive: {
    borderBottomColor: theme.colors.primary,
  },
  tabBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textMuted,
  },
  tabBtnTextActive: {
    color: theme.colors.text,
  },
  discoverContainer: {
    flex: 1,
  },
  discoverScroll: {
    padding: theme.spacing.md,
    alignItems: 'center',
    paddingBottom: 40,
  },
  cardWrapper: {
    alignItems: 'center',
    width: '100%',
    maxWidth: CARD_WIDTH,
  },
  profileCard: {
    width: '100%',
    backgroundColor: 'transparent',
  },
  cardImageWrapper: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#0a0a0a',
    position: 'relative',
    borderRadius: 16,
    overflow: 'hidden',
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  imageNavArea: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
  },
  photoDotsRow: {
    position: 'absolute',
    top: 12,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  photoDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },
  photoDotActive: {
    backgroundColor: '#ffffff',
    width: 8,
  },
  emptyCardImage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCardImageText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginTop: 8,
  },
  cardDetails: {
    paddingVertical: theme.spacing.md,
  },
  cardName: {
    color: theme.colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  cardUsername: {
    color: theme.colors.textMuted,
    fontSize: 13,
    marginTop: 2,
  },
  cardDesc: {
    color: theme.colors.text,
    fontSize: 14,
    lineHeight: 18,
    marginTop: theme.spacing.sm,
  },
  swipeButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    marginTop: 10,
    width: '100%',
  },
  swipeBtn: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: theme.colors.cardBg,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 4,
  },
  swipeBtnControl: {
    borderColor: '#404040',
  },
  swipeBtnPass: {
    borderColor: '#EF4444',
  },
  swipeBtnLike: {
    borderColor: '#10B981',
  },
  likedBadge: {
    backgroundColor: '#10B981',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  likedBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  emptyDiscoverBox: {
    padding: theme.spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 60,
  },
  emptyDiscoverText: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDiscoverSub: {
    color: theme.colors.textMuted,
    fontSize: 13,
    textAlign: 'center',
    marginTop: theme.spacing.xs,
    lineHeight: 18,
    maxWidth: 280,
  },
  refreshBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginTop: 16,
  },
  refreshBtnText: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  matchesScroll: {
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  matchCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.cardBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 12,
  },
  matchCardBody: {
    flex: 1,
    marginLeft: 12,
  },
  matchCardName: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  matchCardUsername: {
    color: theme.colors.textMuted,
    fontSize: 11,
    marginTop: 1,
  },
  matchCardDesc: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginTop: 3,
  },
  profileTabContainer: {
    flex: 1,
    padding: theme.spacing.md,
  },
  activationStatusBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.15)',
    borderRadius: 12,
    padding: 14,
    marginBottom: theme.spacing.md,
  },
  activationStatusBoxActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.05)',
    borderColor: 'rgba(16, 185, 129, 0.15)',
  },
  activationStatusTitle: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  activationStatusDesc: {
    color: theme.colors.textMuted,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 4,
  },
  statusToggleBtn: {
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  statusToggleBtnActivate: {
    backgroundColor: theme.colors.primary,
  },
  statusToggleBtnDeactivate: {
    backgroundColor: theme.colors.error,
  },
  statusToggleBtnText: {
    color: '#000',
    fontSize: 12,
    fontWeight: '700',
  },
  inlineRuleBox: {
    backgroundColor: '#111',
    borderWidth: 1,
    borderColor: '#222',
    borderRadius: 12,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
    gap: 10,
  },
  bigActivateBtn: {
    backgroundColor: theme.colors.primary,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    width: '100%',
  },
  bigActivateBtnText: {
    color: '#000000',
    fontSize: 15,
    fontWeight: '800',
  },
  ruleTitle: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 2,
  },
  ruleItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ruleItemText: {
    color: theme.colors.textMuted,
    fontSize: 11,
    marginLeft: 8,
    flex: 1,
    lineHeight: 15,
  },
  editorForm: {
    backgroundColor: theme.colors.cardBg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.md,
  },
  fieldLabel: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '700',
    marginTop: theme.spacing.xs,
    marginBottom: theme.spacing.xs,
  },
  photosGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginVertical: theme.spacing.xs,
    marginBottom: theme.spacing.md,
  },
  photoSlot: {
    position: 'relative',
    width: 65,
    height: 65,
    borderRadius: 8,
    backgroundColor: '#111',
    borderWidth: 1,
    borderColor: '#333',
    overflow: 'hidden',
  },
  slotImage: {
    width: '100%',
    height: '100%',
  },
  removePhotoBtn: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPhotoSlot: {
    width: 65,
    height: 65,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#333',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputField: {
    backgroundColor: '#111',
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 8,
    padding: 10,
    color: theme.colors.text,
    fontSize: 13,
    marginBottom: theme.spacing.md,
  },
  contactRow: {
    flexDirection: 'column',
    alignItems: 'stretch',
    marginBottom: theme.spacing.sm,
  },
  contactIcon: {
    width: 30,
    textAlign: 'center',
    marginRight: 6,
  },
  saveBtn: {
    backgroundColor: theme.colors.primary,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '700',
  },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  matchPopup: {
    width: '90%',
    maxWidth: 400,
    maxHeight: '85%',
    backgroundColor: theme.colors.cardBg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.lg,
    overflow: 'hidden',
  },
  sparkleHeart: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.md,
  },
  matchPopupTitle: {
    color: '#10B981',
    fontSize: 28,
    fontWeight: '900',
    marginBottom: theme.spacing.xs,
  },
  matchPopupSub: {
    color: theme.colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    marginBottom: theme.spacing.lg,
  },
  matchAvatarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    marginVertical: theme.spacing.sm,
    gap: 16,
  },
  matchAvatarsHeart: {
    position: 'absolute',
    left: '50%',
    marginLeft: -16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.cardBg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  unlockedContactsContainer: {
    width: '100%',
    marginTop: 20,
    gap: 10,
  },
  unlockedContactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
  },
  unlockedContactText: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  closeMatchBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    paddingVertical: 12,
    width: '100%',
    alignItems: 'center',
    marginTop: 20,
  },
  closeMatchBtnText: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  matchDetailCard: {
    backgroundColor: theme.colors.cardBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    width: '90%',
    height: '75%',
    maxWidth: 450,
    overflow: 'hidden',
  },
  matchDetailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  matchDetailHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  matchDetailName: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  matchDetailUsername: {
    color: theme.colors.textMuted,
    fontSize: 12,
  },
  matchDetailPhotosScroll: {
    width: '100%',
    height: 250,
    borderRadius: 12,
    backgroundColor: '#111',
  },
  matchDetailPhoto: {
    width: CARD_WIDTH - 64,
    height: 250,
  },
  emptyDetailPhotoBox: {
    width: '100%',
    height: 150,
    backgroundColor: '#111',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  matchSectionLabel: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '700',
    marginTop: theme.spacing.md,
    marginBottom: theme.spacing.xs,
  },
  matchDetailDescText: {
    color: theme.colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  unmatchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.15)',
    borderRadius: 10,
    paddingVertical: 12,
    marginTop: 24,
  },
  unmatchBtnText: {
    color: theme.colors.error,
    fontSize: 13,
    fontWeight: '700',
  },
  previewSectionHeader: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginTop: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    alignSelf: 'flex-start',
  },
  confirmModalCard: {
    width: '85%',
    maxWidth: 350,
    backgroundColor: theme.colors.cardBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.lg,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 10,
  },
  confirmModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  confirmModalTitle: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  confirmModalDesc: {
    color: theme.colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    marginBottom: theme.spacing.lg,
  },
  confirmModalActions: {
    flexDirection: 'row',
    width: '100%',
    gap: 10,
  },
  confirmModalBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmModalBtnCancel: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: 'transparent',
  },
  confirmModalBtnConfirm: {
    backgroundColor: theme.colors.error,
  },
  confirmModalBtnTextCancel: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  confirmModalBtnTextConfirm: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  contactInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1f1f1f',
    borderWidth: 1,
    borderColor: '#333333',
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: 12,
  },
  contactLabelText: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  contactIconInside: {
    marginRight: 8,
  },
  atBadgeText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
    marginRight: 4,
  },
  contactInputInside: {
    flex: 1,
    color: '#ffffff',
    fontSize: 14,
    paddingVertical: 10,
  },
  extraDetailsList: {
    marginVertical: 6,
    gap: 4,
  },
  extraDetailsHeader: {
    fontSize: 12,
    fontWeight: '800',
    color: theme.colors.primary,
    marginBottom: 4,
  },
  extraDetailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  extraDetailRowText: {
    fontSize: 12,
    lineHeight: 18,
    flex: 1,
  },
});
