export type RootStackParamList = {
  Home: { initialFilterTag?: string; initialPostTags?: string[]; quoteTargetType?: string; quoteTargetId?: string; quoteTargetMeta?: any } | undefined;
  Login: undefined;
  Profile: { userId?: string; title?: string } | undefined;
  Communities: undefined;
  Centers: undefined;
  Teams: undefined;
  Bands: undefined;
  PostDetail: { postId: string };
  UserProfile: { userId: string; title?: string };
  NotFound: undefined;
  Verification: undefined;
  VerifyEmail: undefined;
  ResetPassword: undefined;
  Settings: undefined;
  EditProfile: undefined;
  EditTeam: undefined;
  BlockedUsers: undefined;
  Directory: undefined;
  ConoceBeauchef: undefined;
  Mascotas: { initialTab?: 'explorar' | 'mi-mascota' } | undefined;
  PetDetail: { petId: string };
  Musica: { initialTab?: 'explorar' | 'mi-cancion' } | undefined;
  SongDetail: { songId: string };
  Peliculas: undefined;
  Videojuegos: undefined;
  Libros: undefined;
  Comunidad: undefined;
  Academico: undefined;
  Deportes: undefined;
  Juegos: undefined;
  Students: undefined;
  FollowList: { userId: string; type: 'followers' | 'following' | 'members' | 'recommendations' | 'attendees' | 'poll_voters'; username?: string; title?: string; optionIndex?: number };
  ProblemsList: undefined;
  ProblemDetail: { problemId: string; type?: 'problem' | 'solution' };
  ProblemEditor: { problemId?: string; answerId?: string; type: 'problem' | 'answer'; initialContent?: string; problemTitle?: string };
  Tinder: { initialTab?: 'discover' | 'matches' | 'profile' } | undefined;
  Notifications: undefined;
  LaddersList: undefined;
  LadderDetail: { slug: string; name?: string };
  LadderMatchArbitrator: { slug: string; name?: string; mode?: string; initialMode?: string };
  LadderMatchDetail: { matchId: string; slug?: string; name?: string };
  LadderPlayerProfile: { userId: string; slug: string; name?: string };
  Marketplace: { initialCategory?: string } | undefined;
  MarketplaceItemDetail: { itemId: string };
  SellerProfile: { sellerProfileId?: string; userId?: string };
  SellerProfileEditor: { sellerProfileId?: string } | undefined;
  MarketplaceItemEditor: { itemId?: string } | undefined;
  Activities: { initialTab?: 'following' | 'all' } | undefined;
  ActivityDetail: { activityId: string };
  ActivityEditor: undefined;
  Reviews: undefined;
  CourseDetail: { courseId: string };
  ProfessorDetail: { professorId: string };
  Info: undefined;
  InstallApp: undefined;
  Beaudle: undefined;
  BeaudleDay: { day?: string; name?: string };
  Beaumarket: undefined;
  BeaumarketDetail: { marketId: string; title?: string };
  TeamSchedule: undefined;
  LeaguesList: undefined;
  LeagueDetail: { leagueId: string; name?: string };
  LeagueMatchDetail: { matchId: string };
  LeagueMatchArbitrator: { matchId: string; code?: string };
  TeamProfile: { teamId: string };
  PublicLeagues: undefined;
  PublicLeague: { leagueId: string };
  PublicMatch: { matchId: string };
  PublicTeam: { teamId: string };
  PollasList: undefined;
  Polla: { leagueId: string };
  PollaMatch: { leagueId: string; matchId: string };
  PollaUserBets: { leagueId: string; userId: string };
  NoticiasList: undefined;
  NoticiaDetail: { newsId: string; title?: string };
};
