export type RootStackParamList = {
  Home: { initialFilterTag?: string; initialPostTags?: string[] } | undefined;
  Login: undefined;
  Profile: { userId?: string } | undefined;
  Communities: undefined;
  Centers: undefined;
  Teams: undefined;
  PostDetail: { postId: string };
  UserProfile: { userId: string; title?: string };
  NotFound: undefined;
  Verification: undefined;
  VerifyEmail: undefined;
  ResetPassword: undefined;
  Settings: undefined;
  Directory: undefined;
  Students: undefined;
  FollowList: { userId: string; type: 'followers' | 'following'; username?: string };
  ProblemsList: undefined;
  ProblemDetail: { problemId: string; type?: 'problem' | 'solution' };
  ProblemEditor: { problemId?: string; answerId?: string; type: 'problem' | 'answer'; initialContent?: string; problemTitle?: string };
  Tinder: { initialTab?: 'discover' | 'matches' | 'profile' } | undefined;
  Notifications: undefined;
  LaddersList: undefined;
  LadderDetail: { slug: string; name?: string };
  LadderMatchArbitrator: { slug: string; name?: string };
  LadderMatchDetail: { matchId: string; slug?: string; name?: string };
  LadderPlayerProfile: { userId: string; slug: string; name?: string };
};
